global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'accounts'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'accounts:8080' ]
        labels:
          application: 'accounts'

  - job_name: 'users'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'users:8080' ]
        labels:
          application: 'users'

  - job_name: 'zipkin'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'zipkin:9411' ]
        labels:
          application: 'zipkin'